In [2]:
import tensorflow.keras.layers as layers
import tensorflow as tf
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [3]:
#Use the output of the previous layer as the input of the next layer.
x = tf.keras.Input(shape=(32,))
h1 = layers.Dense(32, activation='relu')(x)
h2 = layers.Dense(32, activation='relu')(h1)
y = layers.Dense(10, activation='softmax')(h2)
model_sample_2 = tf.keras.models.Model(x, y)
#Print model information.
model_sample_2.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │           1,056 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,442 (9.54 KB)

 Trainable params: 2,442 (9.54 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
from tensorflow.keras import layers
import tensorflow as tf

# Create a fully connected (Dense) layer with 32 neurons and sigmoid activation.
layer1 = layers.Dense(32, activation='sigmoid')        # Using activation as string
layer2 = layers.Dense(32, activation=tf.sigmoid)       # Using activation as function object

# Create a Dense layer with He normal initializer for the kernel weights.
layer3 = layers.Dense(32, kernel_initializer=tf.keras.initializers.HeNormal())

# Create a Dense layer with L2 regularization on the kernel weights.
layer4 = layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))

In [8]:
layers.Conv2D(64,[1,1],2,padding='same',activation="relu")

<Conv2D name=conv2d, built=False>

In [9]:
layers.MaxPool2D(pool_size=(2,2),strides=(2,1))

<MaxPooling2D name=max_pooling2d, built=True>

In [10]:
import tensorflow as tf
from tensorflow.keras import layers
import numpy as np

# Define input shape: sequence length = 3, features = 1
inputs = tf.keras.Input(shape=(3, 1))

# LSTM with return_sequences=True returns output at each timestep
lstm_1 = layers.LSTM(1, return_sequences=True)(inputs)
model_lstm_1 = tf.keras.models.Model(inputs=inputs, outputs=lstm_1)

# LSTM with return_sequences=False returns output only at last timestep
inputs = tf.keras.Input(shape=(3, 1))
lstm_2 = layers.LSTM(1, return_sequences=False)(inputs)
model_lstm_2 = tf.keras.models.Model(inputs=inputs, outputs=lstm_2)

# Sample input data: one sequence of length 3 with 1 feature each
data = np.array([[[0.1],
                  [0.2],
                  [0.3]]])

print("Input data:")
print(data)

print("\nOutput when return_sequences=True:")
print(model_lstm_1.predict(data))

print("\nOutput when return_sequences=False:")
print(model_lstm_2.predict(data))


Input data:
[[[0.1]
  [0.2]
  [0.3]]]

Output when return_sequences=True:
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 561ms/step
[[[0.02380481]
  [0.06291228]
  [0.11158288]]]

Output when return_sequences=False:
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 470ms/step
[[-0.02554137]]


In [13]:
#LSTM
tf.keras.layers.LSTM(16, return_sequences=True)
#LSTMCell
x = tf.keras.Input((None, 3))
y = layers.RNN(layers.LSTMCell(16))(x)
model_Istm_3= tf.keras.Model(x, y)

In [16]:
model = tf.keras.Sequential()
model.add(layers.Dense(10, activation='softmax'))

# Compile the model with optimizer, loss function, and metrics
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.categorical_crossentropy,   # fixed typo here
    metrics=[tf.keras.metrics.categorical_accuracy]
)

In [17]:
import numpy as up
train_x = np.random.random((1000, 36))
train_y = np.random.random((1000, 10))
val_x = np.random.random((200, 36))
val_y = np.random.random((200, 10))
model.fit(train_x, train_y, epochs=10, batch_size=100,
validation_data=(val_x, val_y))


Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 76ms/step - categorical_accuracy: 0.1060 - loss: 12.5505 - val_categorical_accuracy: 0.0800 - val_loss: 12.2983
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - categorical_accuracy: 0.1027 - loss: 12.4329 - val_categorical_accuracy: 0.0800 - val_loss: 12.2975
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - categorical_accuracy: 0.1104 - loss: 12.4867 - val_categorical_accuracy: 0.0800 - val_loss: 12.2977
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - categorical_accuracy: 0.1091 - loss: 12.5752 - val_categorical_accuracy: 0.0800 - val_loss: 12.2982
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - categorical_accuracy: 0.1166 - loss: 12.4587 - val_categorical_accuracy: 0.0800 - val_loss: 12.2971
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - categorical_accuracy: 0.1143 - loss: 12.5526 - val_categorical_accuracy: 0.0800 - val_loss: 12.2950
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - categorical_accuracy: 0.1292 

In [18]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()
model.fit(dataset, epochs=10, steps_per_epoch=30,
validation_data=val_dataset, validation_steps=3)

Epoch 1/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - categorical_accuracy: 0.0891 - loss: 12.4020 - val_categorical_accuracy: 0.0833 - val_loss: 12.5731
Epoch 2/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.0977 - loss: 12.4589 - val_categorical_accuracy: 0.0833 - val_loss: 12.5704
Epoch 3/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - categorical_accuracy: 0.1146 - loss: 12.4337 - val_categorical_accuracy: 0.0833 - val_loss: 12.5680
Epoch 4/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.1190 - loss: 12.4939 - val_categorical_accuracy: 0.0833 - val_loss: 12.5664
Epoch 5/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.1170 - loss: 12.3578 - val_categorical_accuracy: 0.0938 - val_loss: 12.5646
Epoch 6/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.1118 - loss: 12.3647 - val_categorical_accuracy: 0.0938 - val_loss: 12.5630
Epoch 7/10
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.1133 - los

In [19]:
import tensorflow as tf

# Set hyperparameters
Epochs = 10

# Define a function for dynamically setting the learning rate
def lr_scheduler(epoch):
    if epoch > 0.9 * Epochs:
        lr = 0.0001
    elif epoch > 0.5 * Epochs:
        lr = 0.001
    elif epoch > 0.25 * Epochs:
        lr = 0.01
    else:
        lr = 0.1
    print(f"Epoch {epoch+1}: Learning rate = {lr}")
    return lr

callbacks = [
    # Early stopping to stop training if validation loss doesn't improve
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        min_delta=1e-2,
        patience=2
    ),
    # Save the best model during training
    tf.keras.callbacks.ModelCheckpoint(
        filepath='testmodel_{epoch}.h5',  # fixed string formatting braces
        save_best_only=True,
        monitor='val_loss'
    ),
    # Dynamically change the learning rate
    tf.keras.callbacks.LearningRateScheduler(lr_scheduler),
    # Use TensorBoard for visualization
    tf.keras.callbacks.TensorBoard(log_dir='./logs')  # fixed missing quotes
]

# Assuming train_x, train_y, val_x, val_y are already defined datasets
model.fit(
    train_x, train_y,
    batch_size=16,
    epochs=Epochs,
    callbacks=callbacks,
    validation_data=(val_x, val_y)
)


Epoch 1: Learning rate = 0.1
Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.1020 - loss: 12.4302 

63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - categorical_accuracy: 0.1020 - loss: 12.4335 - val_categorical_accuracy: 0.0900 - val_loss: 12.4768 - learning_rate: 0.1000
Epoch 2: Learning rate = 0.1
Epoch 2/10
55/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.0727 - loss: 12.6605     

63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - categorical_accuracy: 0.0759 - loss: 12.6693 - val_categorical_accuracy: 0.0850 - val_loss: 12.0813 - learning_rate: 0.1000
Epoch 3: Learning rate = 0.1
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - categorical_accuracy: 0.1130 - loss: 12.6875 - val_categorical_accuracy: 0.0800 - val_loss: 12.5313 - learning_rate: 0.1000
Epoch 4: Learning rate = 0.01
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - categorical_accuracy: 0.0957 - loss: 12.5136 - val_categorical_accuracy: 0.0700 - val_loss: 12.1764 - learning_rate: 0.0100


In [20]:
#Model evaluation
test_x = np.random.random((1000, 36))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)


32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - categorical_accuracy: 0.0932 - loss: 12.4098 


[12.425907135009766, 0.09799999743700027]

In [21]:
#Model prediction
pre_x = np.random.random((10, 36))
result = model.predict(test_x,)
print(result)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step  
[[0.09727675 0.0558443  0.05379843 ... 0.09626088 0.03707112 0.03349301]
 [0.06765126 0.04607787 0.13924839 ... 0.05459872 0.08963976 0.06722113]
 [0.08599975 0.02911919 0.05102163 ... 0.09546943 0.05068332 0.05909768]
 ...
 [0.08501204 0.02062371 0.16910274 ... 0.03979695 0.10915762 0.09414858]
 [0.10712879 0.02279025 0.08913055 ... 0.04695847 0.0551048  0.07221097]
 [0.07504409 0.02211472 0.07505554 ... 0.04873536 0.08687485 0.04000306]]


In [22]:
import numpy as np
import os
import tensorflow as tf

# Create the directory if it does not exist
if not os.path.exists('./model/'):
    os.mkdir('./model/')

# Save the model
model.save('./model/the_saved_model.h5')

# Load the saved model
new_model = tf.keras.models.load_model('./model/the_saved_model.h5')

# Assume test_x and result are predefined NumPy arrays or tensors
new_prediction = new_model.predict(test_x)

# Check that predictions from the original and loaded models are close within tolerance
# atol: absolute tolerance level
np.testing.assert_allclose(result, new_prediction, atol=1e-6)  # Will raise if predictions differ beyond tolerance

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step 


In [26]:


# Save weights with the correct filename ending
model.save_weights('./model/model_weights.weights.h5')

# To load the weights back later
model.load_weights('./model/model_weights.weights.h5')
